apiVersion: apps/v1
kind: Deployment
metadata:
  name: RMG_nginx_deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
        -name: secret-volume
        secret:
          secretName: nginxsecret
      containers:
      - name: nginx
        image: rmg/nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
                 
