apiVersion: v1
kind: Service
metadata:
  name: RMG_nginx
  labels:
    run: nginx
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 80
      protocol: TCP
      name: httpPort
    - PORT: 443
      protocol: TCP
      name: httpsPort
  selector:
    run: nginx
